### ISSUE TITLE
ERROR: No matching distribution found for opencv-contrib-python==4.0.0.21

### ISSUE THREAD

**Issue by appledora** [rayryeng/XiaohuLuVPDetection#8]
I am using opencv-python version `3.4.9.33` and opencv-contrib-python `3.4.9.33`

tried installing through pyPi.
this errror message is thrown :
```
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.0.0.21 (from lu-vp-detect) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56)
ERROR: No matching distribution found for opencv-contrib-python==4.0.0.21
```

**Comment by rayryeng** [comment]
Thanks for this.  Please note that using Python 3.8 or higher produces this error because 4.0.0.21 does not exist.  You will unfortunately need to downgrade your Python distribution in order to run this.  You can set up a virtualenv or conda environment to specify this version prior to installing this vanishing point package.

https://stackoverflow.com/questions/64676116/i-cant-install-opencv-contrib-python-with-pip

It looks like Python 3.7 is the highest to support this package.

**Comment by rayryeng** [comment]
@appledora For the moment, I've added in the README that only versions Python 3.4 to 3.7 are supported should you desire to use OpenCV 4.0.0.21.  Otherwise, any version of 3.x should work.  Can you do me a favour and go into the `setup.py` file and remove the `==4.0.0.21` requirement and point it to your `3.4.9.33` version instead?  I want to make sure it works for 3.x.

**Comment by appledora** [comment]
Hey, I followed your direction and it installed from the repo instead of using pypi. I removed any specification for the opencv-python from the `setup.py` file.
used the same abovementioned versions for `opencv-python` and `opencv-contrib-python`. 
My python version is `3.8.10` 
It worked! Thanks.

**Comment by rayryeng** [comment]
Thanks! I've updated the version on PyPI so that only Python versions 3.4 to 3.7 are supported. Otherwise, you can also install from the repo manually by removing the OpenCV 4.0.0.21 requirement. Good luck!

**Comment by rayryeng** [comment]
Update. The LSD line detection algorithm has been reintroduced into the latest version of OpenCV 4.x as long as you run with Python versions 3.8 and up. This should no longer be an issue.
